In [57]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("All libraries imported successfully!")

All libraries imported successfully!

In [58]:
import os
print("Current Working Directory:")
print(os.getcwd())

print("Files in the current directory:")
print(os.listdir())

print("Files inside data folder:")
print(os.listdir("../data"))

apps = pd.read_csv("../data/googleplaystore.csv")
reviews = pd.read_csv("../data/reviews.csv")

print("Apps dataset shape:", apps.shape)
print("Reviews dataset shape:", reviews.shape)

Current Working Directory:
c:\Users\RAM CHOUDHARY\Desktop\Oasis_Google_Play_Store_Analysis\notebooks
Files in the current directory:
['01_google_play_store_analysis.ipynb', '02_google_play_store_eda.ipynb']
Files inside data folder:
['googleplaystore.csv', 'reviews.csv', 'reviews_clean.csv']
Apps dataset shape: (10841, 13)
Reviews dataset shape: (10800, 13)

In [59]:
# Preview the Apps dataset
print("APPS DATASET")
display(apps.head())

# Preview the Reviews dataset
print("REVIEWS DATASET")
display(reviews.head())

APPS DATASET

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

REVIEWS DATASET

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion,sortOrder,appId
0,f124c390-90c3-4153-9ca1-8e80c0f30a2c,Nathalia Dal Bello,https://play-lh.googleusercontent.com/a-/ACB-R...,"O aplicativo era ótimo, os descontos eram ótim...",1,3753,9.190.0,2023-01-23 20:52:04,NaN,NaN,9.190.0,most_relevant,br.com.brainweb.ifood
1,ce308907-5ebe-493e-b87a-0a12e0f4c1c5,Kenzo Osanai,https://play-lh.googleusercontent.com/a-/ACB-R...,Pior experiência que tive de suporte com um ap...,1,1452,9.191.0,2023-01-31 00:38:30,NaN,NaN,9.191.0,most_relevant,br.com.brainweb.ifood
2,0dc5a70e-8d04-4b5e-84b3-e1bcb922557b,Silvia Miranda,https://play-lh.googleusercontent.com/a-/ACB-R...,Não resolvem o problema do filtro. Filtro para...,1,12,9.204.0,2023-05-03 15:34:29,NaN,NaN,9.204.0,most_relevant,br.com.brainweb.ifood
3,accff4a0-f70e-485a-a85d-04fe3a2e7238,Bárbara Figueiredo,https://play-lh.googleusercontent.com/a-/ACB-R...,"85% das compras chegam erradas, incompletas ou...",1,63,9.204.0,2023-05-01 17:47:53,NaN,NaN,9.204.0,most_relevant,br.com.brainweb.ifood
4,ec2fc975-0f38-4c2e-81c1-7b9dc7398faf,Pedro Renhe,https://play-lh.googleusercontent.com/a/AGNmyx...,"O aplicativo já foi melhor, tinha mais cupons ...",1,37,9.202.1,2023-04-17 23:28:02,NaN,NaN,9.202.1,most_relevant,br.com.brainweb.ifood

In [60]:
# Apps Dataset Information
print("APPS DATASET INFORMATION")
apps.info()

print("\nMissing values in Apps dataset:")
print(apps.isnull().sum())
display(apps.isnull().sum().to_frame("Missing Values"))

APPS DATASET INFORMATION
<class 'pandas.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  str
 1   Category        10841 non-null  str
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  str
 4   Size            10841 non-null  str
 5   Installs        10841 non-null  str
 6   Type            10840 non-null  str
 7   Price           10841 non-null  str
 8   Content Rating  10840 non-null  str
 9   Genres          10841 non-null  str
 10  Last Updated    10841 non-null  str
 11  Current Ver     10833 non-null  str
 12  Android Ver     10838 non-null  str
dtypes: float64(1), str(12)
memory usage: 1.1 MB

Missing values in Apps dataset:
App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

                Missing Values
App                          0
Category                     0
Rating                    1474
Reviews                      0
Size                         0
Installs                     0
Type                         1
Price                        0
Content Rating               1
Genres                       0
Last Updated                 0
Current Ver                  8
Android Ver                  3

In [61]:
# Reviews Dataset Information
print("REVIEWS DATASET INFORMATION")
reviews.info()

print("\nMissing values in Reviews dataset:")
display(reviews.isnull().sum().to_frame("Missing Values"))

REVIEWS DATASET INFORMATION
<class 'pandas.DataFrame'>
RangeIndex: 10800 entries, 0 to 10799
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   reviewId              10800 non-null  str
 1   userName              10800 non-null  str
 2   userImage             10800 non-null  str
 3   content               10800 non-null  str
 4   score                 10800 non-null  int64
 5   thumbsUpCount         10800 non-null  int64
 6   reviewCreatedVersion  9886 non-null   str
 7   at                    10800 non-null  str
 8   replyContent          2402 non-null   str
 9   repliedAt             2402 non-null   str
 10  appVersion            9886 non-null   str
 11  sortOrder             10800 non-null  str
 12  appId                 10800 non-null  str
dtypes: int64(2), str(11)
memory usage: 1.1 MB

Missing values in Reviews dataset:

                      Missing Values
reviewId                           0
userName                           0
userImage                          0
content                            0
score                              0
thumbsUpCount                      0
reviewCreatedVersion             914
at                                 0
replyContent                    8398
repliedAt                       8398
appVersion                       914
sortOrder                          0
appId                              0

In [62]:
display(reviews.head())

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion,sortOrder,appId
0,f124c390-90c3-4153-9ca1-8e80c0f30a2c,Nathalia Dal Bello,https://play-lh.googleusercontent.com/a-/ACB-R...,"O aplicativo era ótimo, os descontos eram ótim...",1,3753,9.190.0,2023-01-23 20:52:04,NaN,NaN,9.190.0,most_relevant,br.com.brainweb.ifood
1,ce308907-5ebe-493e-b87a-0a12e0f4c1c5,Kenzo Osanai,https://play-lh.googleusercontent.com/a-/ACB-R...,Pior experiência que tive de suporte com um ap...,1,1452,9.191.0,2023-01-31 00:38:30,NaN,NaN,9.191.0,most_relevant,br.com.brainweb.ifood
2,0dc5a70e-8d04-4b5e-84b3-e1bcb922557b,Silvia Miranda,https://play-lh.googleusercontent.com/a-/ACB-R...,Não resolvem o problema do filtro. Filtro para...,1,12,9.204.0,2023-05-03 15:34:29,NaN,NaN,9.204.0,most_relevant,br.com.brainweb.ifood
3,accff4a0-f70e-485a-a85d-04fe3a2e7238,Bárbara Figueiredo,https://play-lh.googleusercontent.com/a-/ACB-R...,"85% das compras chegam erradas, incompletas ou...",1,63,9.204.0,2023-05-01 17:47:53,NaN,NaN,9.204.0,most_relevant,br.com.brainweb.ifood
4,ec2fc975-0f38-4c2e-81c1-7b9dc7398faf,Pedro Renhe,https://play-lh.googleusercontent.com/a/AGNmyx...,"O aplicativo já foi melhor, tinha mais cupons ...",1,37,9.202.1,2023-04-17 23:28:02,NaN,NaN,9.202.1,most_relevant,br.com.brainweb.ifood

In [63]:
# Check duplicate Records
print("Apps Dataset")
print("Dupliacte rows:",apps.duplicated().sum())

print("\nReviews Dataset")
print("Duplicate rows:",reviews.duplicated().sum())

Apps Dataset
Dupliacte rows: 483

Reviews Dataset
Duplicate rows: 0

In [64]:
print("Unique app categories:")
print(apps["Category"].nunique())

print("\nApps Types:")
print(apps["Type"].value_counts(dropna = False))

print("\nContent ratings:")
print(apps["Content Rating"].value_counts(dropna = False))

print("\nReview Scores:")
print(reviews["score"].value_counts().sort_values())

Unique app categories:
34

Apps Types:
Type
Free    10039
Paid      800
NaN         1
0           1
Name: count, dtype: int64

Content ratings:
Content Rating
Everyone           8714
Teen               1208
Mature 17+          499
Everyone 10+        414
Adults only 18+       3
Unrated               2
NaN                   1
Name: count, dtype: int64

Review Scores:
score
1    1800
2    1800
4    1800
5    1800
3    3600
Name: count, dtype: int64

In [65]:
# Check Apps dataset before removing duplicates

print("Apps dataset before cleaning:",apps.shape)

# Remove exact duplicate rows
apps = apps.drop_duplicates()
print("Apps dataset after removing duplicates:",apps.shape)

# Verify duplicate removal
print("Remaining duplicate rows:",apps.duplicated().sum())

Apps dataset before cleaning: (10841, 13)
Apps dataset after removing duplicates: (10358, 13)
Remaining duplicate rows: 0

In [66]:
# Check missing values after duplicate removal

display(apps.isnull().sum().to_frame("Missing Values"))

                Missing Values
App                          0
Category                     0
Rating                    1465
Reviews                      0
Size                         0
Installs                     0
Type                         1
Price                        0
Content Rating               1
Genres                       0
Last Updated                 0
Current Ver                  8
Android Ver                  3

In [67]:
# Display rows with missing Type or content rating

print("Rows with missing Type:")
print(apps[apps["Type"].isnull()])

print("\nRows with missing Content Rating:")
display(apps[apps["Content Rating"].isnull()])

Rows with missing Type:
                            App Category  Rating Reviews                Size  \
9148  Command & Conquer: Rivals   FAMILY     NaN       0  Varies with device

     Installs Type Price Content Rating    Genres   Last Updated  \
9148        0  NaN     0   Everyone 10+  Strategy  June 28, 2018

             Current Ver         Android Ver
9148  Varies with device  Varies with device

Rows with missing Content Rating:

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3.0M,"1,000+",Free,0,Everyone,NaN,"February 11, 2018",1.0.19,4.0 and up,NaN

In [68]:
# Check the distribution of app ratings

print("Rating statistics:")
print(apps["Rating"].describe())

print("\nMissing ratings:")
print(apps["Rating"].isnull().sum())

Rating statistics:
count    8893.000000
mean        4.189542
std         0.545452
min         1.000000
25%         4.000000
50%         4.300000
75%         4.500000
max        19.000000
Name: Rating, dtype: float64

Missing ratings:
1465

In [69]:
# Check ratings outside the valid range of 1 to 5

invalid_ratings = apps[(apps["Rating"] < 1) | (apps["Rating"] > 5)]
print("Number of invalid ratings:", len(invalid_ratings))
display(invalid_ratings[["App","Category","Rating","Reviews"]])

Number of invalid ratings: 1

                                           App Category  Rating Reviews
10472  Life Made WI-Fi Touchscreen Photo Frame      1.9    19.0    3.0M

In [70]:
apps.loc[(apps["Rating"]<1) | (apps["Rating"]>5), "Rating"] = np.nan
print("Invalid ratings after cleaning:")
print((apps["Rating"] <1) | (apps["Rating"] >5).sum())
print("\nMissing ratings after cleaning:")
print(apps["Rating"].isnull().sum())

Invalid ratings after cleaning:
0        False
1        False
2        False
3        False
4        False
         ...
10836    False
10837    False
10838    False
10839    False
10840    False
Name: Rating, Length: 10358, dtype: bool

Missing ratings after cleaning:
1466

In [71]:
# Remove rows with missing type or Content Rating
apps = apps.dropna(subset =["Type","Content Rating"])
print("Dataset shape after cleaning:",apps.shape)
print("\nMissing values after cleaning:")
display(apps.isnull().sum().to_frame("Missing Values"))

Dataset shape after cleaning: (10356, 13)

Missing values after cleaning:

                Missing Values
App                          0
Category                     0
Rating                    1464
Reviews                      0
Size                         0
Installs                     0
Type                         0
Price                        0
Content Rating               0
Genres                       0
Last Updated                 0
Current Ver                  8
Android Ver                  2

In [72]:
# Final Verification
print("Dataset shape:",apps.shape)
print("\nDuplicate rows:",apps.duplicated().sum())
print("\nRating range")
print("Minimum rating:",apps["Rating"].min())
print("Maximum rating:",apps["Rating"].max())
print("\nMissing values:")
print(apps.isnull().sum())

Dataset shape: (10356, 13)

Duplicate rows: 0

Rating range
Minimum rating: 1.0
Maximum rating: 5.0

Missing values:
App                  0
Category             0
Rating            1464
Reviews              0
Size                 0
Installs             0
Type                 0
Price                0
Content Rating       0
Genres               0
Last Updated         0
Current Ver          8
Android Ver          2
dtype: int64

In [73]:
# Inspect rows with missing Current Ver

print("Rows with missing Current Ver:")
display(apps[apps["Current Ver"].isnull()][["App","Category","Current Ver","Android Ver"]])

# Inspect rows with missing Android Ver

print("Rows with missing Android Ver:")
display(apps[apps["Android Ver"].isnull()][["App","Category","Current Ver","Android Ver"]])

Rows with missing Current Ver:

,App,Category,Current Ver,Android Ver
15,Learn To Draw Kawaii Characters,ART_AND_DESIGN,NaN,4.2 and up
1553,Market Update Helper,LIBRARIES_AND_DEMO,NaN,1.5 and up
6322,Virtual DJ Sound Mixer,TOOLS,NaN,4.0 and up
6803,BT Master,FAMILY,NaN,1.6 and up
7333,Dots puzzle,FAMILY,NaN,4.0 and up
7407,Calculate My IQ,FAMILY,NaN,2.3 and up
7730,UFO-CQ,TOOLS,NaN,2.0 and up
10342,La Fe de Jesus,BOOKS_AND_REFERENCE,NaN,3.0 and up

Rows with missing Android Ver:

                         App         Category Current Ver Android Ver
4453  [substratum] Vacuum: P  PERSONALIZATION         4.4         NaN
4490    Pi Dark [substratum]  PERSONALIZATION         1.1         NaN

In [74]:
# Check the percentage of missing values
missing_percentage = (apps.isnull().sum() / len(apps) * 100).round(2)
display(missing_percentage[missing_percentage > 0].to_frame("Missing Percentage (%)"))

             Missing Percentage (%)
Rating                        14.14
Current Ver                    0.08
Android Ver                    0.02

In [75]:
# Final missing value check

print("Missing values after cleaning:")
display(apps.isnull().sum().to_frame("Missing Values"))
print("\nDataset shape:",apps.shape)
print("Duplicate rows:",apps.duplicated().sum())

Missing values after cleaning:

                Missing Values
App                          0
Category                     0
Rating                    1464
Reviews                      0
Size                         0
Installs                     0
Type                         0
Price                        0
Content Rating               0
Genres                       0
Last Updated                 0
Current Ver                  8
Android Ver                  2

Dataset shape: (10356, 13)
Duplicate rows: 0

In [76]:
#Check data types of Apps dataset
print("Data Types before Conversion:")
print(apps.dtypes)
print("\nSample records:")
display(apps.head())

Data Types before Conversion:
App                   str
Category              str
Rating            float64
Reviews               str
Size                  str
Installs              str
Type                  str
Price                 str
Content Rating        str
Genres                str
Last Updated          str
Current Ver           str
Android Ver           str
dtype: object

Sample records:

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [77]:
# Convert Reviews column to numeric
apps["Reviews"] = pd.to_numeric(apps["Reviews"],errors = "coerce")

# Verify the conversion
print("Reviews data type:",apps["Reviews"].dtypes)
display(apps[["App","Reviews"]].head())

Reviews data type: int64

                                                 App  Reviews
0     Photo Editor & Candy Camera & Grid & ScrapBook      159
1                                Coloring book moana      967
2  U Launcher Lite – FREE Live Cool Themes, Hide ...    87510
3                              Sketch - Draw & Paint   215644
4              Pixel Draw - Number Art Coloring Book      967

In [78]:
# Clean and convert installs column

apps["Installs"] = (apps["Installs"].str.replace(",","",regex = False).str.replace("+","",regex = False))
apps["Installs"] = pd.to_numeric(apps["Installs"],errors = "coerce")

#verify
print("Installs data type:",apps["Installs"].dtypes)
display(apps[["App","Installs"]].head())

Installs data type: int64

                                                 App  Installs
0     Photo Editor & Candy Camera & Grid & ScrapBook     10000
1                                Coloring book moana    500000
2  U Launcher Lite – FREE Live Cool Themes, Hide ...   5000000
3                              Sketch - Draw & Paint  50000000
4              Pixel Draw - Number Art Coloring Book    100000

In [79]:
# Clean and convert Price column
apps["Price"] = (apps["Price"].astype(str).str.replace("$","", regex = False))
apps["Price"] = pd.to_numeric(apps["Price"],errors="coerce")

# verify
print("Price data type:",apps["Price"].dtype)
display(apps[["App","Price"]].head())

Price data type: float64

                                                 App  Price
0     Photo Editor & Candy Camera & Grid & ScrapBook    0.0
1                                Coloring book moana    0.0
2  U Launcher Lite – FREE Live Cool Themes, Hide ...    0.0
3                              Sketch - Draw & Paint    0.0
4              Pixel Draw - Number Art Coloring Book    0.0

In [80]:
# Check whether paid app price are preserved

print("Price data type:",apps["Price"].dtype)
print("Number of free apps:",(apps["Price"]==0).sum())
print("Number of paid apps:",(apps["Price"]>0).sum())
display(apps.loc[apps["Price"]>0,["App","Price"]].head(10))

Price data type: float64
Number of free apps: 9591
Number of paid apps: 765

                                                   App  Price
234      TurboScan: scan documents and receipts in PDF   4.99
235                     Tiny Scanner Pro: PDF Doc Scan   4.99
427                                 Puffin Browser Pro   3.99
476                          Moco+ - Chat, Meet People   3.99
477                                         Calculator   6.99
478                                  Truth or Dare Pro   1.49
479    Private Dating, Hide App- Blue for PrivacyHider   2.99
480                               Ad Blocker for SayHi   3.99
481  AMBW Dating App: Asian Men Black Women Interra...   7.99
571                          Moco+ - Chat, Meet People   3.99

In [81]:
# Verify numerical columns

print("Reviews:",apps["Reviews"].dtype)
print("Installs:",apps["Installs"].dtype)
print("Price:",apps["Price"].dtype)
display(apps[["App","Reviews","Installs","Price"]].head())

Reviews: int64
Installs: int64
Price: float64

                                                 App  Reviews  Installs  Price
0     Photo Editor & Candy Camera & Grid & ScrapBook      159     10000    0.0
1                                Coloring book moana      967    500000    0.0
2  U Launcher Lite – FREE Live Cool Themes, Hide ...    87510   5000000    0.0
3                              Sketch - Draw & Paint   215644  50000000    0.0
4              Pixel Draw - Number Art Coloring Book      967    100000    0.0

In [82]:
# Check the size column

print("Size data type:",apps["Size"].dtype)
print("Sample size values:")
print(apps["Size"].value_counts().head(15))
print("\nMissing values:",apps["Size"].isnull().sum())

Size data type: str
Sample size values:
Size
Varies with device    1525
11M                    188
12M                    186
13M                    186
14M                    182
15M                    174
17M                    155
26M                    145
16M                    143
19M                    135
10M                    133
25M                    131
20M                    131
21M                    130
24M                    129
Name: count, dtype: int64

Missing values: 0

In [83]:
import numpy as np
import pandas as pd
def convert_size(size):
    if pd.isna(size):
        return np.nan
    size = str(size).strip()
    if size =="Values with device":
        return np.nan
    try:
        if size.endswith("M"):
            return float(size[:-1])
        elif size.endswith("k"):
            return float(size[:-1]) / 1024
        else: 
            return np.nan
    except ValueError:
        return np.nan

apps["Size_MB"]=apps["Size"].apply(convert_size)
print("New Size_MB column data type:",apps["Size_MB"].dtype)
display(apps[["App","Size","Size_MB"]].head(10))

New Size_MB column data type: float64

                                                 App  Size  Size_MB
0     Photo Editor & Candy Camera & Grid & ScrapBook   19M     19.0
1                                Coloring book moana   14M     14.0
2  U Launcher Lite – FREE Live Cool Themes, Hide ...  8.7M      8.7
3                              Sketch - Draw & Paint   25M     25.0
4              Pixel Draw - Number Art Coloring Book  2.8M      2.8
5                         Paper flowers instructions  5.6M      5.6
6            Smoke Effect Photo Maker - Smoke Editor   19M     19.0
7                                   Infinite Painter   29M     29.0
8                               Garden Coloring Book   33M     33.0
9                      Kids Paint Free - Drawing Fun  3.1M      3.1

In [84]:
# Check the Last Updated column

print("Last Updated data type:",apps["Last Updated"].dtype)
print("\nSample dates:")
display(apps[["App","Last Updated"]].head(10))
print("\nMissing dates:",apps["Last Updated"].isnull().sum())

Last Updated data type: str

Sample dates:

                                                 App        Last Updated
0     Photo Editor & Candy Camera & Grid & ScrapBook     January 7, 2018
1                                Coloring book moana    January 15, 2018
2  U Launcher Lite – FREE Live Cool Themes, Hide ...      August 1, 2018
3                              Sketch - Draw & Paint        June 8, 2018
4              Pixel Draw - Number Art Coloring Book       June 20, 2018
5                         Paper flowers instructions      March 26, 2017
6            Smoke Effect Photo Maker - Smoke Editor      April 26, 2018
7                                   Infinite Painter       June 14, 2018
8                               Garden Coloring Book  September 20, 2017
9                      Kids Paint Free - Drawing Fun        July 3, 2018

Missing dates: 0

In [85]:
# Convert the Last Updated to datetime format

apps["Last Updated"] = pd.to_datetime(apps["Last Updated"],errors="coerce")
print("New data type:",apps["Last Updated"].dtype)
print("\n Sample converted dates:")
display(apps[["App","Last Updated"]].head(10))

New data type: datetime64[us]

 Sample converted dates:

                                                 App Last Updated
0     Photo Editor & Candy Camera & Grid & ScrapBook   2018-01-07
1                                Coloring book moana   2018-01-15
2  U Launcher Lite – FREE Live Cool Themes, Hide ...   2018-08-01
3                              Sketch - Draw & Paint   2018-06-08
4              Pixel Draw - Number Art Coloring Book   2018-06-20
5                         Paper flowers instructions   2017-03-26
6            Smoke Effect Photo Maker - Smoke Editor   2018-04-26
7                                   Infinite Painter   2018-06-14
8                               Garden Coloring Book   2017-09-20
9                      Kids Paint Free - Drawing Fun   2018-07-03

In [86]:
# check Current Ver column

print("Current Ver data type:",apps["Current Ver"].dtype)
print("\nSample values:")
print(apps["Current Ver"].value_counts().head(15))
print("\nMissing values:",apps["Current Ver"].isnull().sum())

Current Ver data type: str

Sample values:
Current Ver
Varies with device    1301
1.0                    802
1.1                    260
1.2                    177
2.0                    149
1.3                    142
1.0.0                  135
1.0.1                  115
1.4                     87
1.5                     81
1.0.2                   80
1.6                     65
1.0.3                   61
2.1                     59
3.0                     59
Name: count, dtype: int64

Missing values: 8

In [87]:
# check Android Ver column

print("Android Ver data type:",apps["Android Ver"].dtype)
print("\nSample values:")
print(apps["Android Ver"].value_counts().head(15))
print("\nMissing values:",apps["Android Ver"].isnull().sum())

Android Ver data type: str

Sample values:
Android Ver
4.1 and up            2379
4.0.3 and up          1451
4.0 and up            1337
Varies with device    1220
4.4 and up             894
2.3 and up             643
5.0 and up             546
4.2 and up             387
2.3.3 and up           279
2.2 and up             239
3.0 and up             237
4.3 and up             235
2.1 and up             133
1.6 and up             116
6.0 and up              58
Name: count, dtype: int64

Missing values: 2

In [88]:
# Handle missing version information

apps["Current Ver"] = apps["Current Ver"].fillna("Unknown")
apps["Android Ver"] = apps["Android Ver"].fillna("Unknown")

# Verify the changes
print("Missing values in Current Ver:",apps["Current Ver"].isnull().sum())
print("Missing values in Android Ver:",apps["Android Ver"].isnull().sum())

Missing values in Current Ver: 0
Missing values in Android Ver: 0

In [89]:
# Final data-quality verification

print("Dataset shape:",apps.shape)
print("\nDuplicated rows:",apps.duplicated().sum())
print("\nMissing values in each column:")
display(apps.isnull().sum().to_frame("Missing Values"))
print("\nData types:")
print(apps.dtypes)

Dataset shape: (10356, 14)

Duplicated rows: 0

Missing values in each column:

                Missing Values
App                          0
Category                     0
Rating                    1464
Reviews                      0
Size                         0
Installs                     0
Type                         0
Price                        0
Content Rating               0
Genres                       0
Last Updated                 0
Current Ver                  0
Android Ver                  0
Size_MB                   1525

Data types:
App                          str
Category                     str
Rating                   float64
Reviews                    int64
Size                         str
Installs                   int64
Type                         str
Price                    float64
Content Rating               str
Genres                       str
Last Updated      datetime64[us]
Current Ver                  str
Android Ver                  str
Size_MB                  float64
dtype: object

In [90]:
# Check missing ratings
print("Missing ratings:",apps["Rating"].isnull().sum())
print("Available ratings:",apps["Rating"].notnull().sum())
print("Percentage of missing ratings:",round(apps["Rating"].isnull().mean()*100,2),"%")

Missing ratings: 1464
Available ratings: 8892
Percentage of missing ratings: 14.14 %

In [91]:
# Final Verification

print("Dataset shape:",apps.shape)
print("\nDuplicate rows:",apps.duplicated().sum())
print("\nRating range:")
print("Minimum:",apps["Rating"].min())
print("Maximum:",apps["Rating"].max())
print("\nNumerical column data types:")
print(apps[["Rating","Reviews","Installs","Price","Size_MB"]].dtypes)

Dataset shape: (10356, 14)

Duplicate rows: 0

Rating range:
Minimum: 1.0
Maximum: 5.0

Numerical column data types:
Rating      float64
Reviews       int64
Installs      int64
Price       float64
Size_MB     float64
dtype: object

In [92]:
# Reviews dataset - Initial inspection

print("Dataset shape:",reviews.shape)
print("\nColumn Names:")
print(reviews.columns.tolist())
print("\nDataset Information:")
reviews.info()
print("\nFirst 5 records:")
display(reviews.head())
print("\nStatistical Summary:")
display(reviews.describe(include="all").T)

Dataset shape: (10800, 13)

Column Names:
['reviewId', 'userName', 'userImage', 'content', 'score', 'thumbsUpCount', 'reviewCreatedVersion', 'at', 'replyContent', 'repliedAt', 'appVersion', 'sortOrder', 'appId']

Dataset Information:
<class 'pandas.DataFrame'>
RangeIndex: 10800 entries, 0 to 10799
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   reviewId              10800 non-null  str
 1   userName              10800 non-null  str
 2   userImage             10800 non-null  str
 3   content               10800 non-null  str
 4   score                 10800 non-null  int64
 5   thumbsUpCount         10800 non-null  int64
 6   reviewCreatedVersion  9886 non-null   str
 7   at                    10800 non-null  str
 8   replyContent          2402 non-null   str
 9   repliedAt             2402 non-null   str
 10  appVersion            9886 non-null   str
 11  sortOrder             10800 non-null  str
 12  appId                 10800 non-null  str
dtypes: int64(2), str(11)
memory usage: 1.1 MB

First 5 records:

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion,sortOrder,appId
0,f124c390-90c3-4153-9ca1-8e80c0f30a2c,Nathalia Dal Bello,https://play-lh.googleusercontent.com/a-/ACB-R...,"O aplicativo era ótimo, os descontos eram ótim...",1,3753,9.190.0,2023-01-23 20:52:04,NaN,NaN,9.190.0,most_relevant,br.com.brainweb.ifood
1,ce308907-5ebe-493e-b87a-0a12e0f4c1c5,Kenzo Osanai,https://play-lh.googleusercontent.com/a-/ACB-R...,Pior experiência que tive de suporte com um ap...,1,1452,9.191.0,2023-01-31 00:38:30,NaN,NaN,9.191.0,most_relevant,br.com.brainweb.ifood
2,0dc5a70e-8d04-4b5e-84b3-e1bcb922557b,Silvia Miranda,https://play-lh.googleusercontent.com/a-/ACB-R...,Não resolvem o problema do filtro. Filtro para...,1,12,9.204.0,2023-05-03 15:34:29,NaN,NaN,9.204.0,most_relevant,br.com.brainweb.ifood
3,accff4a0-f70e-485a-a85d-04fe3a2e7238,Bárbara Figueiredo,https://play-lh.googleusercontent.com/a-/ACB-R...,"85% das compras chegam erradas, incompletas ou...",1,63,9.204.0,2023-05-01 17:47:53,NaN,NaN,9.204.0,most_relevant,br.com.brainweb.ifood
4,ec2fc975-0f38-4c2e-81c1-7b9dc7398faf,Pedro Renhe,https://play-lh.googleusercontent.com/a/AGNmyx...,"O aplicativo já foi melhor, tinha mais cupons ...",1,37,9.202.1,2023-04-17 23:28:02,NaN,NaN,9.202.1,most_relevant,br.com.brainweb.ifood

Statistical Summary:

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
reviewId,10800,9413,0dc5a70e-8d04-4b5e-84b3-e1bcb922557b,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
userName,10800,8506,Um usuário do Google,690,NaN,NaN,NaN,NaN,NaN,NaN,NaN
userImage,10800,8685,https://play-lh.googleusercontent.com/EGemoI2N...,690,NaN,NaN,NaN,NaN,NaN,NaN,NaN
content,10800,8943,Muito bom,48,NaN,NaN,NaN,NaN,NaN,NaN,NaN
score,10800.0,NaN,NaN,NaN,3.0,1.291054,1.0,2.0,3.0,4.0,5.0
thumbsUpCount,10800.0,NaN,NaN,NaN,12.35963,89.801715,0.0,0.0,0.0,1.0,3753.0
reviewCreatedVersion,9886,780,3.10.3,515,NaN,NaN,NaN,NaN,NaN,NaN,NaN
at,10800,9409,2023-05-01 01:31:32,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
replyContent,2402,1022,"Olá, você pode enviar mais detalhes dessa situ...",431,NaN,NaN,NaN,NaN,NaN,NaN,NaN
repliedAt,2402,2126,2022-01-31 17:48:07,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
appVersion,9886,780,3.10.3,515,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sortOrder,10800,2,most_relevant,5400,NaN,NaN,NaN,NaN,NaN,NaN,NaN
appId,10800,9,br.com.brainweb.ifood,1200,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [93]:
# Check Missing values

print("Missing Values in Each Column:")
display(reviews.isnull().sum().to_frame(name="Missing Values"))
print("\nMissing value Percentage:")
missing_percentage = ( reviews.isnull().mean()*100).round(2)
display(missing_percentage[missing_percentage > 0].to_frame(name="Missing Percentage(%)"))

Missing Values in Each Column:

                      Missing Values
reviewId                           0
userName                           0
userImage                          0
content                            0
score                              0
thumbsUpCount                      0
reviewCreatedVersion             914
at                                 0
replyContent                    8398
repliedAt                       8398
appVersion                       914
sortOrder                          0
appId                              0

Missing value Percentage:

                      Missing Percentage(%)
reviewCreatedVersion                   8.46
replyContent                          77.76
repliedAt                             77.76
appVersion                             8.46

In [94]:
# Check duplicates

print("Total Duplicate Rows:",reviews.duplicated().sum())
print("\nDuplicate Review IDs:")
print(reviews["reviewId"].duplicated().sum())

Total Duplicate Rows: 0

Duplicate Review IDs:
1387

In [95]:
# Investigate duplicate review IDs

print("Total rows:",len(reviews))
print("Unique review IDs:",reviews["reviewId"].nunique())
print("Duplicate rows based on reviewId:",reviews["reviewId"].duplicated().sum())
print("Number of review IDs appearing more than once:",(reviews["reviewId"].value_counts() > 1).sum())

# display duplicate records
duplicate_reviews = reviews[reviews["reviewId"].duplicated(keep=False)].sort_values("reviewId")
display(duplicate_reviews.head(10))

Total rows: 10800
Unique review IDs: 9413
Duplicate rows based on reviewId: 1387
Number of review IDs appearing more than once: 1387

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion,sortOrder,appId
3138,00231e45-f93c-4362-ba17-5a8ab721c400,Caio Iovanovich (L. H.),https://play-lh.googleusercontent.com/a-/ACB-R...,A parte de selecionar os restaurantes está bug...,3,2,3.19.0,2022-12-05 21:21:11,NaN,NaN,3.19.0,newest,com.mcdo.mcdonalds
2856,00231e45-f93c-4362-ba17-5a8ab721c400,Caio Iovanovich (L. H.),https://play-lh.googleusercontent.com/a-/ACB-R...,A parte de selecionar os restaurantes está bug...,3,2,3.19.0,2022-12-05 21:21:11,NaN,NaN,3.19.0,most_relevant,com.mcdo.mcdonalds
5401,002c279b-50e6-4322-a968-efea8a09f525,Edu Almeida,https://play-lh.googleusercontent.com/a-/ACB-R...,"Falta melhorar, onde se coloca a localização c...",3,0,2.0.26,2023-01-19 16:21:02,"Olá, Edu! Agradecemos por nos avisar.\nEnquant...",2023-01-23 15:35:10,2.0.26,newest,com.xiaojukeji.didi.brazil.customer
5201,002c279b-50e6-4322-a968-efea8a09f525,Edu Almeida,https://play-lh.googleusercontent.com/a-/ACB-R...,"Falta melhorar, onde se coloca a localização c...",3,0,2.0.26,2023-01-19 16:21:02,"Olá, Edu! Agradecemos por nos avisar.\nEnquant...",2023-01-23 15:35:10,2.0.26,most_relevant,com.xiaojukeji.didi.brazil.customer
3077,005a498c-49ef-48c2-87af-3eb00ff6f117,Antonio Vicente,https://play-lh.googleusercontent.com/a-/ACB-R...,"Culpa nem é do App, porém fiz o pedido demorou...",3,0,3.21.1,2023-02-05 22:04:17,NaN,NaN,3.21.1,newest,com.mcdo.mcdonalds
2996,005a498c-49ef-48c2-87af-3eb00ff6f117,Antonio Vicente,https://play-lh.googleusercontent.com/a-/ACB-R...,"Culpa nem é do App, porém fiz o pedido demorou...",3,0,3.21.1,2023-02-05 22:04:17,NaN,NaN,3.21.1,most_relevant,com.mcdo.mcdonalds
8567,0087f89f-088a-4714-a65b-9f5d85b4cc6d,Amanda Stoco,https://play-lh.googleusercontent.com/a-/ACB-R...,"App ruim, lento e sempre dá erro. Aparece opçã...",1,2,3.14.4,2023-04-24 22:26:38,NaN,NaN,3.14.4,newest,burgerking.com.br.appandroid
8409,0087f89f-088a-4714-a65b-9f5d85b4cc6d,Amanda Stoco,https://play-lh.googleusercontent.com/a-/ACB-R...,"App ruim, lento e sempre dá erro. Aparece opçã...",1,2,3.14.4,2023-04-24 22:26:38,NaN,NaN,3.14.4,most_relevant,burgerking.com.br.appandroid
2587,00e1a87f-6106-4a5d-ae56-e4f7dab19266,Rosangela Andrade,https://play-lh.googleusercontent.com/a-/ACB-R...,"Ontem, 22/04/2023 fiz meu primeiro (e último) ...",1,10,3.25.1,2023-04-23 16:29:20,NaN,NaN,3.25.1,newest,com.mcdo.mcdonalds
2405,00e1a87f-6106-4a5d-ae56-e4f7dab19266,Rosangela Andrade,https://play-lh.googleusercontent.com/a-/ACB-R...,"Ontem, 22/04/2023 fiz meu primeiro (e último) ...",1,10,3.25.1,2023-04-23 16:29:20,NaN,NaN,3.25.1,most_relevant,com.mcdo.mcdonalds

In [96]:
# Validate review scores

print("Score data type:",reviews["score"].dtype)
print("\nScore Distribution:")
display(reviews["score"].value_counts().sort_index())
print("\nMinimum score:",reviews["score"].min())
print("\nMaximum score:",reviews["score"].max())
print("\nInavlid scores:",(~reviews["score"].between(1,5)).sum())

Score data type: int64

Score Distribution:

score
1    1800
2    1800
3    3600
4    1800
5    1800
Name: count, dtype: int64

Minimum score: 1

Maximum score: 5

Inavlid scores: 0

In [97]:
# Compare records with repeated review IDs

duplicate_reviews = reviews[reviews["reviewId"].duplicated(keep=False)].sort_values("reviewId")

# Inspect important columns
display(duplicate_reviews[["reviewId","content","score","at","appId"]].head(20))

,reviewId,content,score,at,appId
3138,00231e45-f93c-4362-ba17-5a8ab721c400,A parte de selecionar os restaurantes está bug...,3,2022-12-05 21:21:11,com.mcdo.mcdonalds
2856,00231e45-f93c-4362-ba17-5a8ab721c400,A parte de selecionar os restaurantes está bug...,3,2022-12-05 21:21:11,com.mcdo.mcdonalds
5401,002c279b-50e6-4322-a968-efea8a09f525,"Falta melhorar, onde se coloca a localização c...",3,2023-01-19 16:21:02,com.xiaojukeji.didi.brazil.customer
5201,002c279b-50e6-4322-a968-efea8a09f525,"Falta melhorar, onde se coloca a localização c...",3,2023-01-19 16:21:02,com.xiaojukeji.didi.brazil.customer
3077,005a498c-49ef-48c2-87af-3eb00ff6f117,"Culpa nem é do App, porém fiz o pedido demorou...",3,2023-02-05 22:04:17,com.mcdo.mcdonalds
2996,005a498c-49ef-48c2-87af-3eb00ff6f117,"Culpa nem é do App, porém fiz o pedido demorou...",3,2023-02-05 22:04:17,com.mcdo.mcdonalds
8567,0087f89f-088a-4714-a65b-9f5d85b4cc6d,"App ruim, lento e sempre dá erro. Aparece opçã...",1,2023-04-24 22:26:38,burgerking.com.br.appandroid
8409,0087f89f-088a-4714-a65b-9f5d85b4cc6d,"App ruim, lento e sempre dá erro. Aparece opçã...",1,2023-04-24 22:26:38,burgerking.com.br.appandroid
2587,00e1a87f-6106-4a5d-ae56-e4f7dab19266,"Ontem, 22/04/2023 fiz meu primeiro (e último) ...",1,2023-04-23 16:29:20,com.mcdo.mcdonalds
2405,00e1a87f-6106-4a5d-ae56-e4f7dab19266,"Ontem, 22/04/2023 fiz meu primeiro (e último) ...",1,2023-04-23 16:29:20,com.mcdo.mcdonalds
9462,0127c91e-d7fa-4be8-8ea3-31a7514c6355,"muito bom o app, prático e facil",5,2023-04-26 15:46:14,burgerking.com.br.appandroid
9566,0127c91e-d7fa-4be8-8ea3-31a7514c6355,"muito bom o app, prático e facil",5,2023-04-26 15:46:14,burgerking.com.br.appandroid
10745,0153de1d-f548-4a5f-a6bb-312f0e0c01ee,O melhor App para pedir delivery. O Atendiment...,5,2023-04-30 18:26:23,com.vanuatu.aiqfome
10606,0153de1d-f548-4a5f-a6bb-312f0e0c01ee,O melhor App para pedir delivery. O Atendiment...,5,2023-04-30 18:26:23,com.vanuatu.aiqfome
9788,01a147da-9a41-4bd3-9337-f40fed03e141,Válido a proposta. Mas o intuito de ter essa f...,1,2023-04-08 00:25:34,com.vanuatu.aiqfome
9609,01a147da-9a41-4bd3-9337-f40fed03e141,Válido a proposta. Mas o intuito de ter essa f...,1,2023-04-08 00:25:34,com.vanuatu.aiqfome
9598,01bbc17c-3272-4994-ae11-c30d1649bf4e,O Burger king do shopping Sul é acima da média...,5,2023-04-22 23:30:30,burgerking.com.br.appandroid
9440,01bbc17c-3272-4994-ae11-c30d1649bf4e,O Burger king do shopping Sul é acima da média...,5,2023-04-22 23:30:30,burgerking.com.br.appandroid
8139,0216bd99-8280-4ae8-af86-db3047286cfe,Adoro quando recebo os créditos ajuda muito em...,4,2023-03-13 12:56:00,com.grability.rappi
8017,0216bd99-8280-4ae8-af86-db3047286cfe,Adoro quando recebo os créditos ajuda muito em...,4,2023-03-13 12:56:00,com.grability.rappi

In [98]:
# Convert review date to datetime

reviews["at"] =pd.to_datetime(reviews["at"],errors="coerce")
print("Date Data type:",reviews["at"].dtype)
print("Missing dates:",reviews["at"].isnull().sum())
display(reviews[["reviewId","at"]].head())

Date Data type: datetime64[us]
Missing dates: 0

                               reviewId                  at
0  f124c390-90c3-4153-9ca1-8e80c0f30a2c 2023-01-23 20:52:04
1  ce308907-5ebe-493e-b87a-0a12e0f4c1c5 2023-01-31 00:38:30
2  0dc5a70e-8d04-4b5e-84b3-e1bcb922557b 2023-05-03 15:34:29
3  accff4a0-f70e-485a-a85d-04fe3a2e7238 2023-05-01 17:47:53
4  ec2fc975-0f38-4c2e-81c1-7b9dc7398faf 2023-04-17 23:28:02

In [99]:
# Check whether duplicate review IDs belong to different apps

duplicate_reviews = reviews[
    reviews["reviewId"].duplicated(keep=False)
]

app_id_counts = (
    duplicate_reviews.groupby("reviewId")["appId"]
    .nunique()
)

print(
    "Duplicate IDs associated with multiple apps:",
    (app_id_counts > 1).sum()
)

print(
    "Duplicate IDs associated with one app:",
    (app_id_counts == 1).sum()
)

Duplicate IDs associated with multiple apps: 0
Duplicate IDs associated with one app: 1387

In [100]:
# Check exact duplicates across all columns

print(
    "Exact duplicate rows:",
    reviews.duplicated().sum()
)

# Check duplicates across important review fields
review_key_columns = [
    "reviewId",
    "content",
    "score",
    "at",
    "appId"
]

print(
    "Duplicates across review fields:",
    reviews.duplicated(
        subset=review_key_columns
    ).sum()
)

Exact duplicate rows: 0
Duplicates across review fields: 1387

In [101]:
# Count review IDs that appear more than once

review_id_counts = reviews["reviewId"].value_counts()

repeated_review_ids = review_id_counts[
    review_id_counts > 1
]

print(
    "Number of distinct repeated review IDs:",
    len(repeated_review_ids)
)

print(
    "Total occurrences of repeated review IDs:",
    repeated_review_ids.sum()
)

print(
    "Extra occurrences beyond the first:",
    (repeated_review_ids - 1).sum()
)

print("\nFrequency of repeated IDs:")
print(repeated_review_ids.value_counts().sort_index())

Number of distinct repeated review IDs: 1387
Total occurrences of repeated review IDs: 2774
Extra occurrences beyond the first: 1387

Frequency of repeated IDs:
count
2    1387
Name: count, dtype: int64

In [102]:
# Select the important review fields

review_key_columns = [
    "reviewId",
    "content",
    "score",
    "at",
    "appId"
]

# Display repeated records for investigation

duplicate_reviews = reviews[
    reviews["reviewId"].duplicated(keep=False)
].sort_values("reviewId")

display(
    duplicate_reviews[
        review_key_columns + [
            "userName",
            "thumbsUpCount"
        ]
    ].head(20)
)

,reviewId,content,score,at,appId,userName,thumbsUpCount
3138,00231e45-f93c-4362-ba17-5a8ab721c400,A parte de selecionar os restaurantes está bug...,3,2022-12-05 21:21:11,com.mcdo.mcdonalds,Caio Iovanovich (L. H.),2
2856,00231e45-f93c-4362-ba17-5a8ab721c400,A parte de selecionar os restaurantes está bug...,3,2022-12-05 21:21:11,com.mcdo.mcdonalds,Caio Iovanovich (L. H.),2
5401,002c279b-50e6-4322-a968-efea8a09f525,"Falta melhorar, onde se coloca a localização c...",3,2023-01-19 16:21:02,com.xiaojukeji.didi.brazil.customer,Edu Almeida,0
5201,002c279b-50e6-4322-a968-efea8a09f525,"Falta melhorar, onde se coloca a localização c...",3,2023-01-19 16:21:02,com.xiaojukeji.didi.brazil.customer,Edu Almeida,0
3077,005a498c-49ef-48c2-87af-3eb00ff6f117,"Culpa nem é do App, porém fiz o pedido demorou...",3,2023-02-05 22:04:17,com.mcdo.mcdonalds,Antonio Vicente,0
2996,005a498c-49ef-48c2-87af-3eb00ff6f117,"Culpa nem é do App, porém fiz o pedido demorou...",3,2023-02-05 22:04:17,com.mcdo.mcdonalds,Antonio Vicente,0
8567,0087f89f-088a-4714-a65b-9f5d85b4cc6d,"App ruim, lento e sempre dá erro. Aparece opçã...",1,2023-04-24 22:26:38,burgerking.com.br.appandroid,Amanda Stoco,2
8409,0087f89f-088a-4714-a65b-9f5d85b4cc6d,"App ruim, lento e sempre dá erro. Aparece opçã...",1,2023-04-24 22:26:38,burgerking.com.br.appandroid,Amanda Stoco,2
2587,00e1a87f-6106-4a5d-ae56-e4f7dab19266,"Ontem, 22/04/2023 fiz meu primeiro (e último) ...",1,2023-04-23 16:29:20,com.mcdo.mcdonalds,Rosangela Andrade,10
2405,00e1a87f-6106-4a5d-ae56-e4f7dab19266,"Ontem, 22/04/2023 fiz meu primeiro (e último) ...",1,2023-04-23 16:29:20,com.mcdo.mcdonalds,Rosangela Andrade,10
9462,0127c91e-d7fa-4be8-8ea3-31a7514c6355,"muito bom o app, prático e facil",5,2023-04-26 15:46:14,burgerking.com.br.appandroid,Juliana Pereira,0
9566,0127c91e-d7fa-4be8-8ea3-31a7514c6355,"muito bom o app, prático e facil",5,2023-04-26 15:46:14,burgerking.com.br.appandroid,Juliana Pereira,0
10745,0153de1d-f548-4a5f-a6bb-312f0e0c01ee,O melhor App para pedir delivery. O Atendiment...,5,2023-04-30 18:26:23,com.vanuatu.aiqfome,Talita Souza,0
10606,0153de1d-f548-4a5f-a6bb-312f0e0c01ee,O melhor App para pedir delivery. O Atendiment...,5,2023-04-30 18:26:23,com.vanuatu.aiqfome,Talita Souza,0
9788,01a147da-9a41-4bd3-9337-f40fed03e141,Válido a proposta. Mas o intuito de ter essa f...,1,2023-04-08 00:25:34,com.vanuatu.aiqfome,Jhessie Fejes,0
9609,01a147da-9a41-4bd3-9337-f40fed03e141,Válido a proposta. Mas o intuito de ter essa f...,1,2023-04-08 00:25:34,com.vanuatu.aiqfome,Jhessie Fejes,0
9598,01bbc17c-3272-4994-ae11-c30d1649bf4e,O Burger king do shopping Sul é acima da média...,5,2023-04-22 23:30:30,burgerking.com.br.appandroid,Sara Batista,0
9440,01bbc17c-3272-4994-ae11-c30d1649bf4e,O Burger king do shopping Sul é acima da média...,5,2023-04-22 23:30:30,burgerking.com.br.appandroid,Sara Batista,0
8139,0216bd99-8280-4ae8-af86-db3047286cfe,Adoro quando recebo os créditos ajuda muito em...,4,2023-03-13 12:56:00,com.grability.rappi,Ingrid Souza,0
8017,0216bd99-8280-4ae8-af86-db3047286cfe,Adoro quando recebo os créditos ajuda muito em...,4,2023-03-13 12:56:00,com.grability.rappi,Ingrid Souza,0

In [103]:
# Keep the first occurrence of each review ID

reviews_clean = reviews.drop_duplicates(
    subset=["reviewId"],
    keep="first"
).copy()

print("Original dataset shape:", reviews.shape)
print("Cleaned dataset shape:", reviews_clean.shape)

print(
    "Remaining duplicate review IDs:",
    reviews_clean["reviewId"].duplicated().sum()
)

Original dataset shape: (10800, 13)
Cleaned dataset shape: (9413, 13)
Remaining duplicate review IDs: 0

In [104]:
# Check missing values in the cleaned reviews dataset

print("Cleaned dataset shape:", reviews_clean.shape)

print("\nMissing values in each column:")
display(
    reviews_clean.isnull()
    .sum()
    .to_frame(name="Missing Values")
)

# Calculate missing value percentages
missing_percentage = (
    reviews_clean.isnull().mean() * 100
).round(2)

print("\nMissing value percentages:")
display(
    missing_percentage[missing_percentage > 0]
    .to_frame(name="Missing Percentage (%)")
)

Cleaned dataset shape: (9413, 13)

Missing values in each column:

                      Missing Values
reviewId                           0
userName                           0
userImage                          0
content                            0
score                              0
thumbsUpCount                      0
reviewCreatedVersion             883
at                                 0
replyContent                    7284
repliedAt                       7284
appVersion                       883
sortOrder                          0
appId                              0

Missing value percentages:

                      Missing Percentage (%)
reviewCreatedVersion                    9.38
replyContent                           77.38
repliedAt                              77.38
appVersion                              9.38

In [105]:
# Check empty review text

empty_reviews = (
    reviews_clean["content"]
    .fillna("")
    .str.strip()
    .eq("")
    .sum()
)

print("Empty review texts:", empty_reviews)

print(
    "Missing review texts:",
    reviews_clean["content"].isnull().sum()
)

Empty review texts: 0
Missing review texts: 0

In [106]:
# Convert review dates to datetime

reviews_clean["at"] = pd.to_datetime(
    reviews_clean["at"],
    errors="coerce",
    utc=True
)

print("Review date data type:", reviews_clean["at"].dtype)

print("\nSample review dates:")
display(
    reviews_clean[["content", "score", "at"]].head(10)
)

print(
    "\nMissing review dates:",
    reviews_clean["at"].isnull().sum()
)

Review date data type: datetime64[us, UTC]

Sample review dates:

,content,score,at
0,"O aplicativo era ótimo, os descontos eram ótim...",1,2023-01-23 20:52:04+00:00
1,Pior experiência que tive de suporte com um ap...,1,2023-01-31 00:38:30+00:00
2,Não resolvem o problema do filtro. Filtro para...,1,2023-05-03 15:34:29+00:00
3,"85% das compras chegam erradas, incompletas ou...",1,2023-05-01 17:47:53+00:00
4,"O aplicativo já foi melhor, tinha mais cupons ...",1,2023-04-17 23:28:02+00:00
5,Pior aplicativo de delivery que já usei na min...,1,2023-04-29 14:43:27+00:00
6,Tenho 2 reembolsos aprovados que nãl foram efe...,1,2023-05-03 15:39:28+00:00
7,O aplicativo é horrível para se ter problemas ...,1,2023-04-23 22:07:41+00:00
8,A partir das duas últimas atualizações o meu a...,1,2023-05-02 23:00:47+00:00
9,"Depois de 40min. tentando abrir o app,só abre ...",1,2023-05-01 14:34:25+00:00

Missing review dates: 0

In [107]:
# Final verification of the cleaned reviews dataset

print("Final dataset shape:", reviews_clean.shape)

print(
    "\nDuplicate review IDs:",
    reviews_clean["reviewId"].duplicated().sum()
)

print(
    "Exact duplicate rows:",
    reviews_clean.duplicated().sum()
)

print(
    "Missing review text:",
    reviews_clean["content"].isnull().sum()
)

print(
    "Empty review text:",
    reviews_clean["content"]
    .fillna("")
    .str.strip()
    .eq("")
    .sum()
)

print(
    "Invalid review scores:",
    (~reviews_clean["score"].between(1, 5)).sum()
)

print(
    "Missing review dates:",
    reviews_clean["at"].isnull().sum()
)

Final dataset shape: (9413, 13)

Duplicate review IDs: 0
Exact duplicate rows: 0
Missing review text: 0
Empty review text: 0
Invalid review scores: 0
Missing review dates: 0

In [108]:
# Save the cleaned reviews dataset

reviews_clean.to_csv(
    "../data/reviews_clean.csv",
    index=False
)

print("Cleaned reviews dataset saved successfully!")

Cleaned reviews dataset saved successfully!